# Generated by Django 6.0.3 on 2026-03-15 08:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Institution Name')),
                ('type', models.CharField(choices=[('university', 'University'), ('tvet', 'Tvet'), ('college', 'College'), ('vocational', 'Vocational')], default='university', max_length=100)),
                ('county', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('verified', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'type', 'county'), name='unique_institution_name_county')],
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Campus Name')),
                ('county', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='institutions.institution')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicUnit',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Just a academic unit name', max_length=255, verbose_name='Academic Unit Name')),
                ('type', models.CharField(choices=[('college', 'College'), ('school', 'School'), ('faculty', 'Faculty'), ('department', 'Department')], default='college', max_length=100)),
                ('county', models.CharField(blank=True, max_length=200, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_academicunits', to='institutions.campus')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institution_academicunits', to='institutions.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Program Name')),
                ('level', models.CharField(choices=[('certificate', 'Certificate'), ('diploma', 'Diploma'), ('degree', 'Degree'), ('masters', 'Masters')], default='degree', max_length=100)),
                ('duration_years', models.PositiveIntegerField(default=4)),
                ('academic_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='institutions.academicunit')),
            ],
        ),
        migrations.AddConstraint(
            model_name='campus',
            constraint=models.UniqueConstraint(fields=('name', 'institution', 'county'), name='unique_campus_institution_name_county'),
        ),
        migrations.AddConstraint(
            model_name='academicunit',
            constraint=models.UniqueConstraint(fields=('name', 'campus', 'type'), name='unique_campus_academic_unit_name_county'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(fields=('academic_unit', 'name', 'level'), name='unique_academic_unit_name_level'),
        ),
    ]
